version: "3"

tasks:
  generate:
    aliases:
      - gen
    cmds:
      - protoc -I proto proto/*.proto --go_out=./proto --go_opt=paths=source_relative --go-grpc_out=./proto --go-grpc_opt=paths=source_relative
  run:
    cmds:
      - go run cmd/tg-store/main.go
